### ISSUE TITLE
SPARUL updates: HTTP response encoding expectations too restrictive

### ISSUE THREAD

**Issue by u-u-h** [paulovn/sparql-kernel#16]
When using an %endpoint to submit SparQL Update (SPARUL) update statements like `LOAD`, the [W3C spec](https://www.w3.org/TR/sparql11-update/) does not specify much about the response format. Some implementations like [CGE](http://www.cray.com/products/analytics/cray-graph-engine) return no useful HTTP body, with a "200 OK" or "204 No Content" code and a content body format of text/html. That seems permitted by the spec.

The current implementation sets the acceptable mime types (connection.py:36 and following) to application/sparql-results+json , text/rdf or similar, but cannot deal with text/* in general.

It would be good to either introduce an '%update-endpoint' and use that for SPARUL commands, or at least have a %format specifier that can be set near SPARUL commands to handle the no-result situation appropriately.

--uuh

**Comment by paulovn** [comment]
You are right. I wasn't thinking on SPARQL Update when developing the code, so it is not considered.

https://github.com/paulovn/sparql-kernel/pull/17 should fix this. Specifically:
* Now a specific format is requested only for SELECT, CONSTRUCT or DESCRIBE queries
* In any case, if the automatic format selection fails, it is always possible to use a `%format any` magic to suppress format checking

Tell me if it works. Thanks for detecting this.

**Comment by paulovn** [comment]
Should be fixed in version 1.0.5
