### ISSUE TITLE
How to configure number of result rows?

### ISSUE THREAD

**Issue by jpullmann** [paulovn/sparql-kernel#35]
Hi Paulo, the result tables are pruned by 20 items (e.g. Total: 39, Shown: 20). Is there a means enabling the display of a max. configured number of result rows (comparable to `display.max_rows` in pandas)?

**Comment by paulovn** [comment]
Indeed there is. You can use the `%show` magic, as in:

    %show N

to show a maximum of N results. Or 

    %show all

to show all results. Use it in a cell on its own, or in a line at the beginning of a SPARQL cell.

**Comment by jpullmann** [comment]
Thanks, this hint helped!
